plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'app.vitanahealth.pinnedhttp'
version = '0.1.0'

dependencies {
  implementation "com.squareup.okhttp3:okhttp:4.12.0"
  testImplementation "junit:junit:4.13.2"
}

android {
  namespace "app.vitanahealth.pinnedhttp"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }

  lintOptions {
    abortOnError false
  }
}
