export interface LabMarkerCatalogEntry {
  marker: string;
  unit: string;
}

export const LAB_MARKER_CATALOG: LabMarkerCatalogEntry[] = [
  { marker: "Total cholesterol", unit: "mg/dL" },
  { marker: "LDL cholesterol", unit: "mg/dL" },
  { marker: "HDL cholesterol", unit: "mg/dL" },
  { marker: "Triglycerides", unit: "mg/dL" },
  { marker: "Apolipoprotein B (ApoB)", unit: "mg/dL" },
  { marker: "hsCRP", unit: "mg/L" },
  { marker: "Glucose", unit: "mg/dL" },
  { marker: "Hemoglobin A1c (HbA1c)", unit: "%" },
  { marker: "Insulin", unit: "µIU/mL" },
  { marker: "Alanine aminotransferase (ALT)", unit: "U/L" },
  { marker: "Testosterone", unit: "ng/dL" },
  { marker: "Free testosterone", unit: "pg/mL" },
  { marker: "Sex hormone-binding globulin (SHBG)", unit: "nmol/L" },
  { marker: "Cortisol", unit: "µg/dL" },
  { marker: "DHEAS", unit: "µg/dL" },
  { marker: "TSH", unit: "µIU/mL" },
  { marker: "Estradiol", unit: "pg/mL" },
  { marker: "Progesterone", unit: "ng/mL" },
  { marker: "Vitamin D (25-OH)", unit: "ng/mL" },
  { marker: "Magnesium", unit: "mg/dL" },
  { marker: "RBC magnesium", unit: "mg/dL" },
  { marker: "White blood cell count (WBC)", unit: "10^3/µL" },
  { marker: "Neutrophils", unit: "%" },
  { marker: "Basophils", unit: "%" },
  { marker: "Eosinophils", unit: "%" },
  { marker: "Lymphocytes", unit: "%" },
  { marker: "Monocytes", unit: "%" },
  { marker: "Ferritin", unit: "ng/mL" },
  { marker: "Aspartate aminotransferase (AST)", unit: "U/L" },
  { marker: "Gamma-glutamyl transferase (GGT)", unit: "U/L" },
  { marker: "Albumin", unit: "g/dL" },
  { marker: "Creatine kinase (CK)", unit: "U/L" },
  { marker: "Sodium", unit: "mmol/L" },
  { marker: "Potassium", unit: "mmol/L" },
  { marker: "Vitamin B12", unit: "pg/mL" },
  { marker: "Folate", unit: "ng/mL" },
  { marker: "Hemoglobin", unit: "g/dL" },
  { marker: "Platelets", unit: "10^3/µL" },
  { marker: "Transferrin saturation (TS)", unit: "%" },
  { marker: "Total iron-binding capacity (TIBC)", unit: "µg/dL" },
  { marker: "Iron", unit: "µg/dL" },
  { marker: "Hematocrit", unit: "%" },
  { marker: "Red blood cell count (RBC)", unit: "10^6/µL" },
  { marker: "Mean cell hemoglobin (MCH)", unit: "pg" },
  { marker: "Mean cell hemoglobin concentration (MCHC)", unit: "g/dL" },
  { marker: "Mean corpuscular volume (MCV)", unit: "fL" },
  { marker: "Red cell distribution width (RDW)", unit: "%" },
  { marker: "Mean platelet volume (MPV)", unit: "fL" }
];
